apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: careershield-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: careershield-backend
  template:
    metadata:
      labels:
        app: careershield-backend
    spec:
      containers:
      - name: backend
        image: prins05688/careershield-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MODELS_DIR
          value: "./models" # The model is baked into the image by Jenkins now!
        - name: LOGSTASH_HOST
          value: "elk-service"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: careershield-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
