---
- name: Deploy CareerShield to Kubernetes using Roles
  hosts: localhost
  gather_facts: false

  vars:
    # Default values, can be overridden by Jenkins
    backend_image: "prins05688/careershield-backend:latest"
    frontend_image: "prins05688/careershield-frontend:latest"
    k8s_dir: "../k8s"

  roles:
    - common
